config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'sessions/new'
  get 'admins/profile'
  get 'register_donation' => 'admins#register_donation'
  post 'register_donation' => 'admins#save_donation'
  get 'user/profile'
  get 'user/points'
  get 'user/show'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'quit'  => 'sessions#destroy'
  get 'hospitals/info' => 'hospitals#info'
  resources :admins
  resources :donations
  resources :hospitals
  resources :stores
  resources :rewards do
    member do
      patch :retrieve
      put :retrieve
    end
  end
  devise_for :users
  as :user do
    get 'user/profile', :to => 'devise/registrations#edit', :as => :user_root
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :hospital	
  has_secure_password
  validates :adm_username, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/hospital.rb
class Hospital < ApplicationRecord
	has_many :admins
	accepts_nested_attributes_for :admins, :allow_destroy => true
	validates :hosp_name, presence: true, :length => {:minimum => 6 }
	validates :hosp_city, presence: true
	validates :hosp_state, presence: true
	validates :a_plus, presence: true, numericality: true
	validates :a_minus, presence: true, numericality: true
	validates :b_minus, presence: true, numericality: true
	validates :b_plus, presence: true, numericality: true
	validates :o_minus, presence: true, numericality: true
	validates :o_plus, presence: true, numericality: true
	validates :ab_minus, presence: true, numericality: true
	validates :ab_plus, presence: true, numericality: true
	validates :lattitude, numericality: true
	validates :longitude, numericality: true
end

app/models/place.rb
class Place < ApplicationRecord
  =begin
  def full_address
    [pais, cidade, rua].compact.join(‘,’)
  end
  geocoded_by :full_address
  after_validation :geocode, if: ->(obj){
    obj.address.present? and obj.address_changed?
  }
  =end
end

app/models/reward.rb
class Reward < ApplicationRecord
	belongs_to :store

	validates_presence_of :name, :message => " - Nome deve ser preenchido"
	validates_presence_of :category, :message => " - Categoria deve ser preenchido"
	validates_presence_of :quantity, :message => " - Quantidade deve ser preenchido"
	validates_presence_of :cost, :message => " - Valor deve ser preenchido"
	validates :quantity, numericality: { greater_than: 0 }
	validates :cost, numericality: { greater_than: 0 }
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :rewards
	accepts_nested_attributes_for :rewards, :allow_destroy => true

	validates_presence_of :name, :message => " - Deve ser preenchido"
	validates_presence_of :phone, :message => " - Deve ser preenchido"
	validates_presence_of :address, :message => " - Deve ser preenchido"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_save :set_age

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  enum bloodtype: [:'A-',:'A+',:'B-',:'B+',:'AB-',:'AB+',:'O-',:'O+']

  validates :email, uniqueness: true
  validates :weight, :numericality => {greater_than: 0}, presence: true
  validates :height, :numericality => {greater_than: 0}, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthdate, presence: true

  def set_age
    self.age = (Time.now.year - self.birthdate.year) + (Time.now.month >
      self.birthdate.month || Time.now.month == self.birthdate.month &&
      Time.now.day > self.birthdate.day ? 0 : -1)
      if(self.age <= 0)
        errors[:birthdate] << "is invalid."
        false
      end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def profile
  end

  def points
  end

  def nivelsangue (bloodtype,city,state)
    
    bloodbanks = []

    hosps = ""
    case bloodtype
      when "A+"
        bloodbanks = Hospital.where(a_plus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "A-"
        bloodbanks = Hospital.where(a_minus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "B+"
        bloodbanks = Hospital.where(b_plus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "B-"
        bloodbanks = Hospital.where(b_minus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "O+"
        bloodbanks = Hospital.where(o_plus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "O-"
        bloodbanks = Hospital.where(o_minus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "AB+"
        bloodbanks = Hospital.where(ab_plus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "AB-"
        bloodbanks = Hospital.where(ab_minus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      else 
    end 

    if bloodbanks.length == 0
      return ""
    else 
      for i in 0..(bloodbanks.length-1)
        hosps += bloodbanks[i]
        hosps += ", "
      end 
    end
    return hosps
  end
  helper_method :nivelsangue

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in_admin
        session[:admin_id] = @admin.id
    end

    def current_admin
        @current_admin ||= Admin.find_by(id: session[:admin_id])
    end

    def admin_hospital
        @admin_hospital ||= Hospital.find_by(hosp_name: current_admin.hospital_name)
    end

    def block_access
        if current_admin.present?
            redirect_to admins_profile_path
        end
    end

    def sign_out_admin
		session.delete(:admin_id)
		@current_admin = nil
	end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
   <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "erro") %> impediram a atualização das informações:</h2>
      <ul>
        <% admin.errors.full_messages.each do |message| %>
          <%= message %><br/>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex-layout">
    <div class="field flex-cell">
      <label class="pure-material-textfield-outlined">
        <%= form.text_field :adm_username, autofocus: true, :placeholder => " " %>
        <span>Admin Username</span>
      </label>
    </div>
    <div class="field flex-cell">
      <label class="pure-material-textfield-outlined">
        <%= form.text_field :adm_name, autocomplete: "off", :placeholder => " " %>
        <span>Nome</span>
      </label>
    </div>
  </div>
  <div class="flex-layout">
    <div class="field flex-cell">
      <label class="pure-material-textfield-outlined">
        <%= form.text_field :adm_cpf, autocomplete: "off", :placeholder => " " %>
        <span>CPF</span>
      </label>
    </div>
    <div class="field flex-cell">
      <label class="pure-material-textfield-outlined">
        <%= form.text_field :hospital_name, autocomplete: "off", :placeholder => " " %>
        <span>Hospital</span>
      </label>
    </div>
  </div>
  <div class="field flex-layout flex-cell">
    <label class="pure-material-textfield-outlined">
      <%= form.password_field :password, autocomplete: "off", :placeholder => " " %>
      <span>Senha</span>
    </label>
  </div>
  <br/>
  <div class="actions flex-layout flex-cell">
      <%= form.submit "Submeter", :class => "btn btn-danger edit-btn-danger btn-medium" %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<div align="center">
    <h1>Editar Informações</h1>
    <br/>
    <%= render 'form', admin: @admin %>
    <br/>
    <%= link_to 'Back', admins_profile_path %>
</div>

app/views/admins/new.html.erb
<div align="center">
    <h1>Criar Admin</h1>
    <%= render 'form', admin: @admin %>
    <%= link_to 'Voltar', root_path %>
</div>

app/views/admins/profile.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>BlooDiscounts</title>
</head>

<body>
    <div align="center">
        <% if (current_admin) %>
            <h1> Bem vindo </h1>
            <h3><%= current_admin.adm_name %></h3>
            <br/>
            <%= button_to "Registrar doação", register_donation_path, :method => :get,:class => "btn btn-danger edit-btn-danger btn-medium" %>
            <br/>
            <%= button_to "Exibir estoque de sangue", quit_path, :class => "btn btn-danger edit-btn-danger btn-medium"  %>
            <br/>
            <%= button_to "Cadastrar lojas", new_store_path, :method => :get, :class => "btn btn-danger edit-btn-danger btn-medium"  %>
            <br/>
            <%= button_to "Listar produtos de uma loja", stores_path, :method => :get, :class => "btn btn-danger edit-btn-danger btn-medium"  %>
            <br/>
            <%= button_to "Exibir perfil", current_admin, :method => :get,:class => "btn btn-danger edit-btn-danger btn-medium" %>
            <br/>
            <%= button_to "Sair", quit_path ,:method => :delete,:class => "btn btn-danger edit-btn-danger btn-medium" %>
        <% end %>
    </div>
</body>
</html>

app/views/admins/register_donation.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>BlooDiscounts</title>
</head>

<body> 
    <div align="center">
        <% if (current_admin) %>
            <h3> Registrar doação </h3>
           <%= form_for :donor, url: register_donation_path do |f| %>
            <br/>
            <div class="field">
                <label class="pure-material-textfield-outlined">
                    <%= f.number_field :id, autofocus: true,  min: 1,:placeholder => " " %>
                    <span>Id do doador</span>
                </label>
            </div>  
            <br/>
            <div class="actions">
                <%= f.submit "Registrar", :class => "btn btn-danger edit-btn-danger btn-medium" %>
            </div>
             <br/>
            <%= link_to 'Voltar', admins_profile_path %>
        <% end %>
        <% end %>
    </div>
</body>
</html>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
    <h1>Perfil</h1>

    <p class="flex-layout">
    <strong class="flex-cell">Nome do Admin:</strong>
    <%= @admin.adm_name %>
    </p>

    <p class="flex-layout">
    <strong class="flex-cell">Admin Username:</strong>
    <%= @admin.adm_username %>
    </p>

    <p class="flex-layout">
    <strong class="flex-cell">Hospital responsável:</strong>
    <%= @admin.hospital_name %>
    </p>

    <p class="flex-layout">
    <strong class="flex-cell">CPF do Admin:</strong>
    <%= @admin.adm_cpf %>
    </p>

    <%= button_to "Editar informações", edit_admin_path(@admin), :method => :get,:class => "btn btn-danger edit-btn-danger btn-medium" %>
    <br/>
    <%= link_to 'Back', admins_profile_path %>
</div>

app/views/admins/show_blood_table.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>BlooDiscounts</title>
</head>

<body>
    <div align="center">
        <% if (current_admin) %>
        <h1> Estoque de Sangue </h1>
            <% if (admin_hospital) %>
                <p>A+: <%= admin_hospital.a_plus %></p>
                <br/>
                <p>A-: <%= admin_hospital.a_minus %></p>
                <br/>
                <p>B+: <%= admin_hospital.b_plus %></p>
                <br/>
                <p>B-: <%= admin_hospital.b_minus %></p>
                <br/>
                <p>O+: <%= admin_hospital.o_plus %></p>
                <br/>
                <p>O-: <%= admin_hospital.o_minus %></p>
                <br/>
                <p>AB+: <%= admin_hospital.ab_plus %></p>
                <br/>
                <p>AB-: <%= admin_hospital.ab_minus %></p>
                <br/>

            <% end %>
             <br/>
            <%= link_to 'Voltar', admins_profile_path %>
        <% end %>
    </div>
</body>
</html>

app/views/layouts/_alerts.html.erb
<!-- <p class="notice"><%= notice%></p> -->
<!-- <p class="alert"><%= alert %></p> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<html>
  <head>
    <title>BlooDiscounts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--google maps-->
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+'AIzaSyA9OXC-tCO1_qWGcP6v-TZgE2Dz9PWonb4&libraries=geometry' %>
    <%= yield(:head_tags) %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <div align="center">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>	
        <p class="alert alert-danger"><%= alert %></p>	
      <% end %>

    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BlooDiscounts</title>
</head>
<body>
    <div align="center">
        <h1> BlooDiscounts </h1>
        <div class="img-logo">
            <%= image_tag "logo.png" %>
        </div>
        <br/>
        <br/>
      <%= button_to "Cadastrar", new_user_registration_path, :class => "btn btn-danger edit-btn-danger btn-medium", :method => :get %>
        <br/>
        <a>Já possui cadastro? </a>
        <br/>
      <%= link_to  "Entre aqui.", new_user_session_path, class: "btn btn-danger edit-btn-danger"%>
    </div>
</body>
</html>

app/views/welcome/sample.html.erb
<h2>Hello World#Sample</h2>
<p>
  The time is now: <%= Time.now %>
</p>

<%= "Message from controller : #{@controller_message}" %>

<%= link_to("Go to Index", {:action => 'index', :id => 99, :user => 'William Otaku'}) %>