config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'sessions/new'
  get 'admins/profile'
  get 'register_donation' => 'admins#register_donation'
  post 'register_donation' => 'admins#save_donation'
  get 'user/profile'
  get 'user/points'
  get 'user/show'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'quit'  => 'sessions#destroy'
  get 'hospitals/info' => 'hospitals#info'
  resources :admins
  resources :donations
  resources :hospitals
  resources :stores
  resources :rewards do
    member do
      patch :retrieve
      put :retrieve
    end
  end
  devise_for :users
  as :user do
    get 'user/profile', :to => 'devise/registrations#edit', :as => :user_root
  end
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :rewards
	accepts_nested_attributes_for :rewards, :allow_destroy => true

	validates_presence_of :name, :message => " - Deve ser preenchido"
	validates_presence_of :phone, :message => " - Deve ser preenchido"
	validates_presence_of :address, :message => " - Deve ser preenchido"
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    if current_admin.nil?
      redirect_to login_path
      return
    end
    @store = Store.new
    @store.rewards.build
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)
    if params[:add_reward]
      # add empty reward associated with @store
      @store.rewards.build
      render action: :new
    elsif params[:remove_reward]
      render action: :new
    else
      # save goes like usual
      if @store.save
        flash[:notice] = "Loja e produtos cadastrados com sucesso."
        redirect_to admins_profile_path and return
      else
        render action: :new
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    if params[:add_reward]
      @store.rewards.build
    elsif params[:remove_reward]
      # collect all marked for delete reward ids
      @rewards_attributes = []
      params[:store][:rewards_attributes].each do |index, reward_attributes|
        if reward_attributes[:_destroy] == "1"
          @rewards_attributes.push(reward_attributes[:id])
        end
      end
      if !@rewards_attributes.empty?
        puts(@rewards_attributes)
        Reward.delete(@rewards_attributes)
      end
    else
      if @store.update_attributes(store_params)
        flash[:notice] = "Atualizado loja e produtos com sucesso."
        redirect_to admins_profile_path and return
      end
    end
    render :action => 'edit'
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :category, :address, :email, :phone, {rewards_attributes: [:_destroy, :name, :category, :quantity, :cost, :id] } )
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for @store do |form| %>
  <div class="flex-layout">
    <div class="field flex-cell">
      <label class="pure-material-textfield-outlined">
        <%= form.text_field :name, autofocus: true, :placeholder => " " %>
        <span>Nome</span>
      </label>
    </div>
    <div class="field flex-cell">
      <label class="pure-material-textfield-outlined">
        <%= form.text_field :category, autocomplete: "off", :placeholder => " " %>
        <span>Categoria</span>
      </label>
    </div>
  </div>
  <div class="flex-layout">
    <div class="field flex-cell">
      <label class="pure-material-textfield-outlined">
        <%= form.text_field :address, autocomplete: "off", :placeholder => " " %>
        <span>Endereço</span>
      </label>
    </div>
    <div class="field flex-cell">
      <label class="pure-material-textfield-outlined">
        <%= form.text_field :email, autocomplete: "off", :placeholder => " " %>
        <span>Email para contato</span>
      </label>
    </div>
  </div>
  <div class="field flex-layout flex-cell">
    <label class="pure-material-textfield-outlined">
      <%= form.text_field :phone, autocomplete: "off", :placeholder => " " %>
      <span>Telefone para contato</span>
    </label>
  </div>
  <br/>
  <h3>Recompensas</h3>
  <%= form.fields_for :rewards do |re| %>
    <p>
      <%= re.check_box :_destroy %>
      <%= re.label :_destroy, 'Remover' %>
      <div class="flex-layout">
        <div class="field flex-cell">
          <label class="pure-material-textfield-outlined">
            <%= re.text_field :name, autofocus: true, :placeholder => " " %>
            <span>Nome</span>
          </label>
        </div>
        <div class="field flex-cell">
          <label class="pure-material-textfield-outlined">
            <%= re.text_field :category, autocomplete: "off", :placeholder => " " %>
            <span>Categoria</span>
          </label>
        </div>
      </div>
      <div class="flex-layout">
        <div class="field flex-cell">
          <label class="pure-material-textfield-outlined">
            <%= re.number_field :quantity, autofocus: true, step: 0, min: 1, :placeholder => " " %>
            <span>Quantidade</span>
          </label>
        </div>
        <div class="field flex-cell">
          <label class="pure-material-textfield-outlined">
            <%= re.number_field :cost, autocomplete: "off", step: 0, min: 1, :placeholder => " " %>
            <span>Valor</span>
          </label>
        </div>
      </div>
    </p>
  <% end %>
  <p>
    <%= form.submit 'Adicionar outra recompensa', :name => "add_reward", :class => "btn btn-danger edit-btn-danger btn-medium" %>
    <%= form.submit 'Remover recompensas', :name => "remove_reward", :class => "btn btn-danger edit-btn-danger btn-medium" %>
  </p>
  <%= form.submit 'Submeter' ,:class => "btn btn-danger edit-btn-danger btn-medium" %>
  <br/>
  <br/>
<% end %>

app/views/stores/edit.html.erb
<div align="center">
    <h1>Editar loja e suas recompensas</h1>
    <%= render 'form', store: @store %>
    <%= link_to 'Voltar', stores_path %>
<div>

app/views/stores/index.html.erb
<div align="center">
  <p id="notice"><%= notice %></p>

  <h1>Lojas registradas</h1>

  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Categoria</th>
        <th>Endereço</th>
        <th>Email</th>
        <th>Contato</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @stores.each do |store| %>
        <tr>
          <td><%= store.name %></td>
          <td><%= store.category %></td>
          <td><%= store.address %></td>
          <td><%= store.email %></td>
          <td><%= store.phone %></td>
          <td><%= link_to 'Mostrar/Editar loja e  seus produtos', edit_store_path(store) %></td>
          <td><%= link_to 'Deletar', store, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Voltar', admins_profile_path %>
</div>

app/views/stores/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>BlooDiscounts</title>
    <p class="notice"></p>
    <p class="alert"></p>
  </head>
  <body>
    <div align="center">
      <h1>Cadastrar Loja</h1>
      <%= render 'form', store: @store %>
      <%= link_to 'Voltar', admins_profile_path %>
    </div>
  </body>
</html>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @store.category %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @store.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>