config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'sessions/new'
  get 'admins/profile'
  get 'register_donation' => 'admins#register_donation'
  post 'register_donation' => 'admins#save_donation'
  get 'user/profile'
  get 'user/points'
  get 'user/show'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'quit'  => 'sessions#destroy'
  get 'hospitals/info' => 'hospitals#info'
  resources :admins
  resources :donations
  resources :hospitals
  resources :stores
  resources :rewards do
    member do
      patch :retrieve
      put :retrieve
    end
  end
  devise_for :users
  as :user do
    get 'user/profile', :to => 'devise/registrations#edit', :as => :user_root
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:user_cpf, :hospital_name, :donated_amount, :donation_date)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_with(model: donation, local: true) do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
        <% donation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-md-2">
    <%= form.label :user_cpf %>
    <%= form.text_field :user_cpf, class:"form-control" %>
  </div>

  <div class="field col-md-2">
    <%= form.label :hospital_name %>
    <%= form.text_field :hospital_name, class:"form-control" %>
  </div>

  <div class="field col-md-2">
    <%= form.label :donated_amount %>
    <%= form.text_field :donated_amount, class:"form-control" %>
  </div>

  <div class="field col-md-5">
    <%= form.label :donation_date %>
    <%= form.datetime_select :donation_date, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-danger edit-btn-danger btn-medium" %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<div align="center">
  <h1>Editing Donation</h1>

  <%= render 'form', donation: @donation %>

  <%= link_to 'Show', @donation, class: "btn btn-danger edit-btn-danger btn-medium" %>
  <br/>
  <%= link_to raw('<span class="oi oi-arrow-left"></span>Back'), donations_path, class: "btn btn-danger edit-btn-danger" %>
</div>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<div align="center">
<h1>Donations</h1>

<table style="max-width:75%" class="table table-hover">
  <thead>
    <tr>
      <th>User cpf</th>
      <th>Hospital name</th>
      <th>Donated amount</th>
      <th>Donation date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.user_cpf %></td>
        <td><%= donation.hospital_name %></td>
        <td><%= donation.donated_amount %></td>
        <td><%= donation.donation_date %></td>
        <td><%= link_to raw('<span class="oi oi-eye"></span>'), donation %></td>
        <td><%= link_to raw('<span class="oi oi-pencil"></span>'), edit_donation_path(donation) %></td>
        <td><%= link_to raw('<span class="oi oi-x"></span>'), donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to raw('<span class="oi oi-plus"></span>New Donation'), new_donation_path, class: "btn btn-danger edit-btn-danger btn-medium" %>
</div>

app/views/donations/new.html.erb
<div align="center">
  <h1>New Donation</h1>

  <%= render 'form', donation: @donation %>

  <%= link_to raw('<span class="oi oi-arrow-left"></span>Back'), donations_path, class: "btn btn-danger edit-btn-danger" %>
</div>

app/views/donations/show.html.erb
<div align="center">
<p id="notice"><%= notice %></p>

<p>
  <strong>User cpf:</strong>
  <%= @donation.user_cpf %>
</p>

<p>
  <strong>Hospital name:</strong>
  <%= @donation.hospital_name %>
</p>

<p>
  <strong>Donated amount:</strong>
  <%= @donation.donated_amount %>
</p>

<p>
  <strong>Donation date:</strong>
  <%= @donation.donation_date %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation), class: "btn btn-danger edit-btn-danger btn-medium" %>
<br/>
<%= link_to raw('<span class="oi oi-arrow-left"></span>Back'), donations_path, class: "btn btn-danger edit-btn-danger" %>
</div>