config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'sessions/new'
  get 'admins/profile'
  get 'register_donation' => 'admins#register_donation'
  post 'register_donation' => 'admins#save_donation'
  get 'user/profile'
  get 'user/points'
  get 'user/show'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'quit'  => 'sessions#destroy'
  get 'hospitals/info' => 'hospitals#info'
  resources :admins
  resources :donations
  resources :hospitals
  resources :stores
  resources :rewards do
    member do
      patch :retrieve
      put :retrieve
    end
  end
  devise_for :users
  as :user do
    get 'user/profile', :to => 'devise/registrations#edit', :as => :user_root
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_save :set_age

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  enum bloodtype: [:'A-',:'A+',:'B-',:'B+',:'AB-',:'AB+',:'O-',:'O+']

  validates :email, uniqueness: true
  validates :weight, :numericality => {greater_than: 0}, presence: true
  validates :height, :numericality => {greater_than: 0}, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthdate, presence: true

  def set_age
    self.age = (Time.now.year - self.birthdate.year) + (Time.now.month >
      self.birthdate.month || Time.now.month == self.birthdate.month &&
      Time.now.day > self.birthdate.day ? 0 : -1)
      if(self.age <= 0)
        errors[:birthdate] << "is invalid."
        false
      end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def profile
  end

  def points
  end

  def nivelsangue (bloodtype,city,state)
    
    bloodbanks = []

    hosps = ""
    case bloodtype
      when "A+"
        bloodbanks = Hospital.where(a_plus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "A-"
        bloodbanks = Hospital.where(a_minus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "B+"
        bloodbanks = Hospital.where(b_plus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "B-"
        bloodbanks = Hospital.where(b_minus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "O+"
        bloodbanks = Hospital.where(o_plus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "O-"
        bloodbanks = Hospital.where(o_minus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "AB+"
        bloodbanks = Hospital.where(ab_plus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      when "AB-"
        bloodbanks = Hospital.where(ab_minus: + ' < 30', hosp_city: city, hosp_state: state ).pluck(:hosp_name)
      else 
    end 

    if bloodbanks.length == 0
      return ""
    else 
      for i in 0..(bloodbanks.length-1)
        hosps += bloodbanks[i]
        hosps += ", "
      end 
    end
    return hosps
  end
  helper_method :nivelsangue

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_body.html.erb
<div align="center">
    <h1> BlooDiscounts </h1>
    <div class="img-logo">
        <%= image_tag "logo.png" %>
    </div>
    <br/>
    <br/>
</div>

app/views/user/_edit.html.erb
<html lang="en">

<head>
  <%= render "head" %>
</head>

<body>
  <%= render "body" %>

</body>

app/views/user/_head.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>BlooDiscounts</title>

app/views/user/pontos.html.erb
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BlooDiscounts</title>
</head>
<body>
    <div align="center">
        <h1> BlooDiscounts </h1>
        <div class="img-logo">
            <%= image_tag "logo.png" %>
        </div>
        <br/>
        <br/>
        <% if current_user %>
            <p>Você tem <%= current_user.points %> pontos.</p>
            <br/>
            <br/>
        <% end %>
        <%= button_to "Voltar", user_profile_path, :method => :get,
         :class => "custom-button ripple" %>
    </div>
</body>
</html>

app/views/user/profile.html.erb
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BlooDiscounts</title>
</head>
<body>

    

    <div align="center">
        <h1> BlooDiscounts </h1>
        <div class="img-logo">
            <%= image_tag "logo.png" %>
        </div>
        <br/>
        <br/>
        <div class= "center">
            <% if current_user %>
                <h3><%="Olá, " +  current_user.first_name + " " + +  current_user.last_name %></h3>
                <br/>
                <%= button_to "Resgatar pontos", rewards_path, :method => :get,
                :class => "btn btn-danger edit-btn-danger btn-medium" %>
                <%# <%= button_to "Hospitais próximos", :class => "custom-button ripple"  %>
                <br/>

                <%= button_to "Exibir perfil", user_show_path, :method => :get, :class => "btn btn-danger edit-btn-danger btn-medium" %>
                <br/>

                <%= button_to "Sair", destroy_user_session_path, :method => :delete,
                :class => "btn btn-danger edit-btn-danger btn-medium" %>
            <% end %>
            <br/>
            <br/>

            <br/>
            <br/>
            <br/>
            <br/>
            <h3> Bancos de sangue que precisam de seu tipo sanguíneo: <%=  nivelsangue(current_user.bloodtype, current_user.city, current_user.state)  %> </h3>

        </div>

    </div>
</body>

app/views/user/show.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
  <h1>Perfil</h1>
  <p class="flex-layout">
  <strong class="flex-cell">Nome:</strong>
  <%= current_user.first_name + " " + current_user.last_name%>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">Id:</strong>
  <%= current_user.id %>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">Email:</strong>
  <%= current_user.email %>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">Tipo sanguíneo:</strong>
  <%= current_user.bloodtype %>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">Data de nascimento:</strong>
  <%= current_user.birthdate %>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">Idade:</strong>
  <%= current_user.age %>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">Peso:</strong>
  <%= current_user.weight %>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">Altura:</strong>
  <%= current_user.height %>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">Cidade:</strong>
  <%= current_user.city %>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">Estado:</strong>
  <%= current_user.state %>
  </p>

  <p class="flex-layout">
  <strong class="flex-cell">País:</strong>
  <%= current_user.country %>
  </p>
  <br/>
  <%= button_to "Editar informações", edit_user_registration_path, :method => :get,:class => "btn btn-danger edit-btn-danger" %>
  <br/>

    <%= link_to raw('<span class="oi oi-arrow-left"></span>Voltar'), user_profile_path,
          :class => "btn btn-danger edit-btn-danger" %>
</div>